/*
 * This source file was generated by the Gradle 'init' task
 */
package org.openjfx;

import java.net.URL;

import javafx.application.Application;
import javafx.stage.Stage;

public class MainApp extends Application {

    @Override
    public void start(Stage stage) throws Exception {
        // String licenseKey = "OK6AEKNYF27LOP29K9XD04Y24ZWAE3TPS1VO5OQ3N3UFBNXP5GS3MK2JGEGJFR8CRZVURRO59PAFH8P4GXKZ28B99MT5S8TLT5SINFDZFKPZ74ZQVPVB6G9WVG7HYLMVL8QZSFUVJ1GFY348T";
        
        // Engine engine = Engine.newInstance(
            //             EngineOptions.newBuilder(HARDWARE_ACCELERATED)
            //             .licenseKey(licenseKey)
            //             .build());
            
            // engine.newBrowser().navigation().loadUrl("https://www.google.com");
            
            // Browser browser = engine.newBrowser();
            // BrowserView view = BrowserView.newInstance(browser);
            
            
            
            // Scene scene = new Scene(new BorderPane(view), 700, 500);
            
        URL url = getClass().getResource("file:\\C:\\Users\\ashto\\Desktop\\Code\\editor\\app\\src\\main\\resources\\org\\openjfx\\scene.fxml");
        System.out.println("url = " + url);
        // Parent root = FXMLLoader.load(getClass().getResource("scene.fxml"));
        // Scene scene = new Scene(root);
        // scene.getStylesheets().add(getClass().getResource("styles.css").toExternalForm());
        
        // stage.setTitle("JavaFX and Gradle");
        // stage.setScene(scene);
        // stage.show();
        // browser.navigation().loadUrl("https://www.google.com");
        // stage.setOnCloseRequest(event -> engine.close());
    }

    public static void main(String[] args) {
        launch(args);
    }

}